sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ipsacoder/dockerreactapp -f Dockerfile.dev .

script:
  - docker run -e CI=true ipsacoder/dockerreactap npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker'
  env: 'DockerReactapp-env'
  bucket_name: 'elasticbeanstalk-us-east-1-461661633653'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY